#! /bin/bash

function last () {
    arg=
    for i in $@
    do
	arg=$i
    done
    echo $arg
}

file=`last $@`

write-dot-file.rkt $* > $file.dot

maphtml.sh $file.dot $file.html

function get_line () {
    head -$2 $1.dot | tail -1
}

for linenum in `grep -n '^\s*"[^"]*" \[' $file.dot | awk -F : '{print $1}'`
do
    line=`get_line $file $linenum`
    name=`echo $line | grep -o '"[^"]*"' | head -1 | sed 's/"//g'`
    url=`echo $line | grep -o '"[^"]*"' | tail -1 | sed 's/"//g'`
    if [ ! -f $url ]
    then
	cp blank.html $url
	sed -i "s/\$TITLE/$name/g" $url
    fi
done
